spring:
  data:
    redis:
      host: redis
      port: 6379
      password:
      timeout: 60000

  mail:
    host: smtp.gmail.com
    port: 587
    username: mukhammadjonsattarov0425@gmail.com
    password: bbfr mdmh kgux gzay
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  datasource:
    url: jdbc:postgresql://postgres:5432/jwt_demo
    username: postgres
    password: 4778
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
jwt:
  secret: my_super_secret_jwt_key_step_for_good_job
  expiration: 3600000
  refresh-expiration: 604800000
